### ISSUE TITLE
ServiceInstance Spec.parameters is being dropped 

### ISSUE THREAD

**Issue by mhamaydeh** [drycc/service-catalog#11]
# Bug Report 
Yes
**What happened**:
I have deployed service catalog on openshift 4.10 and it works fine , with the helm default values , then applied a yaml to create ServiceInstance .
with OC client , oc create -f <yaml file>
in the ServiceInstance yaml I'm passing Spec.parameters , and when the ServiceInstance is create , the parameters object is empty , looks like it have be unset somehow. 
**What you expected to happen**:
I expect the ServiceInstance will have the user defined Spec parameters  after creation .

**How to reproduce it (as minimally and precisely as possible)**:
deploy the service catalog with the default values using helm , deploy a service broker 
then create ServiceInstance with yaml file which have Spec parameters defined .
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T22:28:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+70fb84c", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-04-25T15:58:12Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
- service-catalog version:
-  version: 0.4.1
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  -  I have installed in on another namespace , and yes i can see cluster-info config map
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
    -  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
    -  requestheader-group-headers: '["X-Remote-Group"]'
    -  requestheader-username-headers: '["X-Remote-User"]'
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
  - Helm with default vaules.yaml
- Are you trying to use ALPHA features? Did you enable them?
-  Helm chart created the CRD's

**Comment by mhamaydeh** [comment]
I found the Issue , By default, all unspecified fields for a custom resource, across all versions, are pruned
I have added  ` x-kubernetes-preserve-unknown-fields: true` to `serviceinstance` crd and it works fine! 

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning

**Comment by dee0sap** [comment]
Hey @mhamaydeh 

I see you closed this issue but I don't see a corresponding pull request or commit.
Would you please point me to the commit or pull request that addressed this issue?

**Comment by mhamaydeh** [comment]
@dee0sap I didn't create a pull request for that , but posted the the link for the kubernetes default behavior and the solution as a reference if someone faced the same issue

**Comment by dee0sap** [comment]
Thanks @mhamaydeh 

My team would like to see this actually fixed in this repo so that we, and others, don't have to patch the CRD before using them.

To that end, I would like to open a PR and tie it to an open issue.   Github isn't giving me the option to reopen this issue, if possible would you be willing to reopen it?    Otherwise I'll just create another issue and point it to this one.

**Comment by mhamaydeh** [comment]
@dee0sap  I have reopened it , FYA

**Comment by duanhongyi** [comment]
#13
