### ISSUE TITLE
release 0.4.2 is not yet pushed to docker hub

### ISSUE THREAD

**Issue by chungmanau** [drycc/service-catalog#15]
# Bug Report 

**What happened**:
I cannot pull 0.4.2 image from docker hub

**What you expected to happen**:
I expect to pull 0.4.2 image from docker hub

**How to reproduce it (as minimally and precisely as possible)**:
execute "docker pull drycc/service-catalog:0.4.2"
get error "Error response from daemon: manifest for drycc/service-catalog:0.4.2 not found: manifest unknown: manifest unknown"

**Anything else we need to know?**:
NA

**Environment**:
- Kubernetes version (use `kubectl version`):
- service-catalog version:
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?

**Comment by duanhongyi** [comment]
@chungmanau  Sorry, please try registry.drycc.cc first. It may be a problem with the synchronization script.

**Comment by duanhongyi** [comment]
@chungmanau Synchronization completed
